version: '3'

services:   # 컨테이너
  frontend:
    container_name: frontend
    build: ./frontend           # build되는 지점 - frontend 폴더
    command: ["npm", "start"]  
    ports:                      # -p 옵션과 동일
      - 3000:3000
    volumes:
      - ./frontend:/app

      
  backend:
    container_name: backend
    build: ./backend
    command: sh -c " python manage.py makemigrations user
      && python manage.py migrate user
      && python manage.py runserver 0.0.0.0:8000"
    # restart: always             # 컨테이너 다운되면 재기동되게끔
    ports:
      - 8000:8000
    volumes:
    - .:/user/src/sunggong

  db:  
    container_name: mysqlDB
    image: mysql:8.0.29
    ports:  
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}" 
    # volumes:
    #   - .:/var/lib/mysql
    command:                                      # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    # restart: always
